package com.mao.healthclub.model;

import java.util.Date;

public class Coach {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.id
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.name
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.sex
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.pic
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.identity
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    private String identity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.birthday
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.feature
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    private String feature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.contract_start
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    private Date contractStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.contract_end
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    private Date contractEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.address
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.experience
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    private Integer experience;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.id
     *
     * @return the value of coach.id
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.id
     *
     * @param id the value for coach.id
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.name
     *
     * @return the value of coach.name
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.name
     *
     * @param name the value for coach.name
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.sex
     *
     * @return the value of coach.sex
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.sex
     *
     * @param sex the value for coach.sex
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.pic
     *
     * @return the value of coach.pic
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.pic
     *
     * @param pic the value for coach.pic
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.identity
     *
     * @return the value of coach.identity
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.identity
     *
     * @param identity the value for coach.identity
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.birthday
     *
     * @return the value of coach.birthday
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.birthday
     *
     * @param birthday the value for coach.birthday
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.feature
     *
     * @return the value of coach.feature
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.feature
     *
     * @param feature the value for coach.feature
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public void setFeature(String feature) {
        this.feature = feature == null ? null : feature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.contract_start
     *
     * @return the value of coach.contract_start
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public Date getContractStart() {
        return contractStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.contract_start
     *
     * @param contractStart the value for coach.contract_start
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public void setContractStart(Date contractStart) {
        this.contractStart = contractStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.contract_end
     *
     * @return the value of coach.contract_end
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public Date getContractEnd() {
        return contractEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.contract_end
     *
     * @param contractEnd the value for coach.contract_end
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public void setContractEnd(Date contractEnd) {
        this.contractEnd = contractEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.address
     *
     * @return the value of coach.address
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.address
     *
     * @param address the value for coach.address
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.experience
     *
     * @return the value of coach.experience
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public Integer getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.experience
     *
     * @param experience the value for coach.experience
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public void setExperience(Integer experience) {
        this.experience = experience;
    }
}