package com.mao.healthclub.model;

import java.util.Date;

public class Custom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.id
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.nickname
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.username
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.password
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.sex
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.birthday
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.phone
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.id
     *
     * @return the value of custom.id
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.id
     *
     * @param id the value for custom.id
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.nickname
     *
     * @return the value of custom.nickname
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.nickname
     *
     * @param nickname the value for custom.nickname
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.username
     *
     * @return the value of custom.username
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.username
     *
     * @param username the value for custom.username
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.password
     *
     * @return the value of custom.password
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.password
     *
     * @param password the value for custom.password
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.sex
     *
     * @return the value of custom.sex
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.sex
     *
     * @param sex the value for custom.sex
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.birthday
     *
     * @return the value of custom.birthday
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.birthday
     *
     * @param birthday the value for custom.birthday
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.phone
     *
     * @return the value of custom.phone
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.phone
     *
     * @param phone the value for custom.phone
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}