package com.mao.healthclub.model;

import java.util.Date;

public class Member_order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_order.id
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_order.custom_id
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private Integer customId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_order.start_date
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_order.end_date
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_order.time
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private Integer time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_order.money
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_order.phone
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_order.trade_number
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private String tradeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_order.pay_status
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private Boolean payStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_order.id
     *
     * @return the value of member_order.id
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_order.id
     *
     * @param id the value for member_order.id
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_order.custom_id
     *
     * @return the value of member_order.custom_id
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public Integer getCustomId() {
        return customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_order.custom_id
     *
     * @param customId the value for member_order.custom_id
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setCustomId(Integer customId) {
        this.customId = customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_order.start_date
     *
     * @return the value of member_order.start_date
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_order.start_date
     *
     * @param startDate the value for member_order.start_date
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_order.end_date
     *
     * @return the value of member_order.end_date
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_order.end_date
     *
     * @param endDate the value for member_order.end_date
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_order.time
     *
     * @return the value of member_order.time
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_order.time
     *
     * @param time the value for member_order.time
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_order.money
     *
     * @return the value of member_order.money
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_order.money
     *
     * @param money the value for member_order.money
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_order.phone
     *
     * @return the value of member_order.phone
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_order.phone
     *
     * @param phone the value for member_order.phone
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_order.trade_number
     *
     * @return the value of member_order.trade_number
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public String getTradeNumber() {
        return tradeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_order.trade_number
     *
     * @param tradeNumber the value for member_order.trade_number
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setTradeNumber(String tradeNumber) {
        this.tradeNumber = tradeNumber == null ? null : tradeNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_order.pay_status
     *
     * @return the value of member_order.pay_status
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public Boolean getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_order.pay_status
     *
     * @param payStatus the value for member_order.pay_status
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setPayStatus(Boolean payStatus) {
        this.payStatus = payStatus;
    }
}