package com.mao.healthclub.model;

public class Orderid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderid.id
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderid.order_id
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderid.id
     *
     * @return the value of orderid.id
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderid.id
     *
     * @param id the value for orderid.id
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderid.order_id
     *
     * @return the value of orderid.order_id
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderid.order_id
     *
     * @param orderId the value for orderid.order_id
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}