package com.mao.healthclub.model;

public class Service {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.id
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.name
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.introduction
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.content
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.pic
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.type
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.id
     *
     * @return the value of service.id
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.id
     *
     * @param id the value for service.id
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.name
     *
     * @return the value of service.name
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.name
     *
     * @param name the value for service.name
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.introduction
     *
     * @return the value of service.introduction
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.introduction
     *
     * @param introduction the value for service.introduction
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.content
     *
     * @return the value of service.content
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.content
     *
     * @param content the value for service.content
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.pic
     *
     * @return the value of service.pic
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.pic
     *
     * @param pic the value for service.pic
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.type
     *
     * @return the value of service.type
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.type
     *
     * @param type the value for service.type
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }
}