package com.mao.healthclub.mapper;

import com.mao.healthclub.model.Course_order;
import com.mao.healthclub.model.Course_orderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface Course_orderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    long countByExample(Course_orderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    int deleteByExample(Course_orderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    int insert(Course_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    int insertSelective(Course_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    List<Course_order> selectByExampleWithRowbounds(Course_orderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    List<Course_order> selectByExample(Course_orderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    Course_order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") Course_order record, @Param("example") Course_orderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    int updateByExample(@Param("record") Course_order record, @Param("example") Course_orderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    int updateByPrimaryKeySelective(Course_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    int updateByPrimaryKey(Course_order record);
}