package com.mao.healthclub.mapper;

import com.mao.healthclub.model.Orderid;
import com.mao.healthclub.model.OrderidExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrderidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    long countByExample(OrderidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    int deleteByExample(OrderidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    int insert(Orderid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    int insertSelective(Orderid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    List<Orderid> selectByExampleWithRowbounds(OrderidExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    List<Orderid> selectByExample(OrderidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    Orderid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") Orderid record, @Param("example") OrderidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    int updateByExample(@Param("record") Orderid record, @Param("example") OrderidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    int updateByPrimaryKeySelective(Orderid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderid
     *
     * @mbg.generated Tue Mar 10 23:02:11 CST 2020
     */
    int updateByPrimaryKey(Orderid record);
}