package com.mao.healthclub.mapper;

import com.mao.healthclub.model.Service;
import com.mao.healthclub.model.ServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    long countByExample(ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    int deleteByExample(ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    int insert(Service record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    int insertSelective(Service record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    List<Service> selectByExampleWithRowbounds(ServiceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    List<Service> selectByExample(ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    Service selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Service record, @Param("example") ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    int updateByExample(@Param("record") Service record, @Param("example") ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    int updateByPrimaryKeySelective(Service record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    int updateByPrimaryKey(Service record);
}