package com.mao.healthclub.mapper;

import com.mao.healthclub.model.Service_price;
import com.mao.healthclub.model.Service_priceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface Service_priceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_price
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    long countByExample(Service_priceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_price
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    int deleteByExample(Service_priceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_price
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_price
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    int insert(Service_price record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_price
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    int insertSelective(Service_price record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_price
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    List<Service_price> selectByExampleWithRowbounds(Service_priceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_price
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    List<Service_price> selectByExample(Service_priceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_price
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    Service_price selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_price
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Service_price record, @Param("example") Service_priceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_price
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    int updateByExample(@Param("record") Service_price record, @Param("example") Service_priceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_price
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    int updateByPrimaryKeySelective(Service_price record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_price
     *
     * @mbg.generated Wed Feb 26 18:35:18 CST 2020
     */
    int updateByPrimaryKey(Service_price record);
}